#!/usr/bin/env node
var conf = require('wilson/conf'),
    commands = require('wilson/commands'),
    path = require('path');

require.paths.push(process.cwd());
conf.setSettingsFile(path.join(__dirname, 'settings.js'));
commands.runcommand();
